# Form implementation generated from reading ui file 'speaker.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_speaker_window(object):
    def setupUi(self, speaker_window):
        speaker_window.setObjectName("speaker_window")
        speaker_window.resize(700, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(speaker_window.sizePolicy().hasHeightForWidth())
        speaker_window.setSizePolicy(sizePolicy)
        speaker_window.setMinimumSize(QtCore.QSize(700, 550))
        speaker_window.setMaximumSize(QtCore.QSize(700, 550))
        self.centralwidget = QtWidgets.QWidget(speaker_window)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 30, 661, 481))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(300)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 91, 16))
        self.label.setObjectName("label")
        speaker_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(speaker_window)
        QtCore.QMetaObject.connectSlotsByName(speaker_window)

    def retranslateUi(self, speaker_window):
        _translate = QtCore.QCoreApplication.translate
        speaker_window.setWindowTitle(_translate("speaker_window", "your library"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("speaker_window", "theme"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("speaker_window", "date"))
        self.label.setText(_translate("speaker_window", "your events:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    speaker_window = QtWidgets.QMainWindow()
    ui = Ui_speaker_window()
    ui.setupUi(speaker_window)
    speaker_window.show()
    sys.exit(app.exec())
